import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from '@/components/Header'
import Footer from "@/components/Footer";
import "../styles/globals.css";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" className="scroll-smooth" suppressHydrationWarning>
      <head>
        <style>{`
          :root {
            --color-primary: 59 130 246;
            --color-primary-dark: 99 102 241;
          }
          @font-face {
            font-family: 'HarmonyOS';
            src: url('/fonts/HarmonyOS_Sans_SC_Medium.ttf');
          }
        `}</style>
      </head>
      <body className="font-sans antialiased transition-colors duration-300">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          {...({} as React.ComponentProps<typeof ThemeProvider>)}
        >
          <div className="flex justify-center">
            <div className="w-full max-w-[1200px] mx-auto">
              <header>
                <Header />
              </header>
              {children}
              <footer className="mt-12 w-full text-center text-sm text-gray-600 dark:text-gray-400 space-y-2">
                <Footer />
              </footer>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}